"""Updated payroll model

Revision ID: bc77718cd309
Revises: 8832a00b81ee
Create Date: 2025-03-17 12:54:43.276685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc77718cd309'
down_revision = '8832a00b81ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('payment_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('payroll_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('salary_amount')
        batch_op.drop_column('notes')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('pay_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pay_date', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('employee_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('salary_amount', mysql.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payroll_ibfk_1', 'users', ['employee_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('amount')
        batch_op.drop_column('department_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
